server:
  port: 8080
  servlet:
    session:
      timeout: 5m  #设置session的有效期为5分钟
  compression:
    enabled: true #开启返回结果压缩，减少传输耗时
    min-response-size: 2KB

spring:
  config:
    import: application-rabbitmq.yml,application-image.yml,application-email.yml,application-config.yml,application-dal.yml,application-web.yml,application-ai.yml
  main:
    allow-circular-references: true  # 允许循环引用
    # 允许多个重名bean进行覆盖，主要是为了实现多数据源功能，自主注册的datasource替换默认的
    allow-bean-definition-overriding: true
  mvc:
    async:
      request-timeout:
  liquibase:
    change-log: classpath:liquibase/master.xml
    enabled: true  # 当实际使用的数据库不支持liquibase, 如 mariadb时，将这个参数设置false
  servlet:
    multipart:  #web 应用中文件上传功能相关配置
      enabled: true
      max-file-size: 5MB
      max-request-size: 10MB

security:
  salt: simple_forum_salt #密码加盐，更安全的做法是每个用户的密码使用独立的盐，并将其保存在用户表中
  salt-index: 3 # 盐插入的位置

forum:
  sensitive:  # 敏感词校验相关配置
    enable: true
    deny:   # 自定义的敏感词，英文逗号分隔
    allow:  # 自定义的非敏感词，英文逗号分隔
  jwt:
    issuer: simple_forum #jwt 签发者
    secret: hello_world  #签名秘钥
    expire: 2592000000   # jwt 的有效期限，默认30天

#默认数据库名
database:
  name: simple_forum

# mybatis 相关统一配置
mybatis-plus:
  configuration:
    #开启下划线转驼峰
    map-underscore-to-camel-case: true

# Knife4j 配置
knife4j:
  # production: true  #开启生产环境屏蔽 这个配置和上面setting配置似乎有点关系，必须在setting配置中配置一个选项，否则会使用改配置会报错， 改配置放在prod环境
  enable: true
  setting:
    language: zh-CN
  openapi:
    title: SimpleForum
    description: 一个基于 Spring Boot、Mybatis-Plus、MySQL、Redis、ElasticSearch、MongoDB、Docker、RabbitMQ 等技术栈实现的社区系统，采用主流的互联网技术架构。
    version: 1.0.0
    concat:
      - qiuyunduo | qyd | 邱运铎
      - http://qiuyunduo.xyz
      - https://github.com/qiuyunduo
    license: Apache License 2.0
    license-url: http://github.com/qiuyunduo
    email: iqiuyunduo@163.com
    group:
      admin:
        group-name: 后台接口分组
        api-rule: package
        api-rule-resources:
          - com.qyd.web.admin
      front:
        group-name: 前台接口分组
        api-rule: package
        api-rule-resources:
          - com.qyd.web.front

logging:
  level:
    com.qyd.service.rank.service.impl.*: debug # 指定具体包下的日志输出级别