image:
  abs-tmp-path: /tmp/storage/
  web-img-path: /forum/image/
  cdn-host:
  oss:
    type: local
    prefix: simpleforum/
    endpoint:
    ak:
    sk:
    bucket:
    host: https://cdn.tobetterjavaer.com

spring:
  web:
    resources:
      # 支持本地图片上传之后的连接，其中file:///d的用于win系统，后面的file: 适用于mac/linux系统
      static-locations:
        - classpath:/static/
        - file:///d:${image.abs-tmp-path}
        - file:${image.abs-tmp-path}